name: drift_notes_dart
description: "Мобильное приложение для рыболовов."
publish_to: 'none'

version: 1.0.2+14

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Добавляем необходимые зависимости
  uuid: ^4.2.2  # Для генерации уникальных идентификаторов

  flutter_image_compress: ^2.0.4  # ← ДОБАВИТЬ ЭТУ СТРОКУ

  # Основные
  cupertino_icons: ^1.0.8

  # Firebase - СТАРЫЕ СОВМЕСТИМЫЕ ВЕРСИИ (без конфликтов Kotlin)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_app_check: ^0.2.2+7  # Совместимая с старыми версиями

  # ДОБАВЛЕНО: In-App Purchase для подписок
  in_app_purchase: ^3.1.13

  # Google Sign-In
  google_sign_in: ^6.2.1

  # UI и дизайн
  intl: 0.20.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0

  # Утилиты
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # Карты
  google_maps_flutter: 2.12.3
  geolocator: ^10.1.0

  # Управление состоянием
  provider: ^6.1.1

  url_launcher: ^6.2.5
  just_audio: ^0.9.36
  audioplayers: ^5.2.1

  # Календарь
  table_calendar: ^3.0.9

  package_info_plus: ^8.0.0  # Последняя версия

  crypto: ^3.0.3

  # ИСПРАВЛЕНО: Разрешения и уведомления
  permission_handler: ^11.1.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

  # Альтернативная библиотека для бейджа
  app_badge_plus: ^1.1.4

  quick_actions: ^1.0.7
  app_links: ^6.3.2

  fl_chart: ^0.68.0

  # ДОБАВЛЕНО: Isar для офлайн базы данных (проверенные версии)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

  # Безопасные dev-зависимости
  mockito: ^5.4.2
  build_runner: ^2.4.7

  # ДОБАВЛЕНО: Isar генератор кода (проверенная версия)
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  # Assets для приложения
  assets:
    - assets/images/
    - assets/shops/
    - assets/images/fishing_types/
    - assets/sounds/
    - assets/localization/  # Файлы локализации
    - assets/localization/geography/
    - assets/images/drawer_logo.png
    - assets/icon/
    - assets/user_guide/

    # ✅ ОБНОВЛЕНО: Автоматическое включение всех файлов политик
    - assets/privacy_policy/
    - assets/terms_of_service/

# ОБНОВЛЕННАЯ КОНФИГУРАЦИЯ ИКОНОК
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  # АДАПТИВНЫЕ ИКОНКИ ДЛЯ ANDROID (исправляют проблему с белым фоном)
  adaptive_icon_background: "#0A2E29"  # Цвет фона из вашей темы
  adaptive_icon_foreground: "assets/icon/foreground.png"  # Логотип с прозрачным фоном

  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#0A2E29"
    theme_color: "#0A2E29"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"