// Путь: lib/services/tournament_service.dart

import '../models/tournament_model.dart';

class TournamentService {
  static final TournamentService _instance = TournamentService._internal();
  factory TournamentService() => _instance;
  TournamentService._internal();

  // Все турниры на 2025 год
  List<TournamentModel> getAllTournaments() {
    return [
      // === ОФИЦИАЛЬНЫЕ СОРЕВНОВАНИЯ ===

      // ГОРОДСКИЕ МЕРОПРИЯТИЯ Г.АЛМАТЫ
      TournamentModel(
        id: 'official_city_1',
        name: 'Чемпионат г. Алматы по спортивному подледному лову рыбы на мормышку',
        startDate: DateTime(2025, 1, 17),
        endDate: DateTime(2025, 1, 19),
        duration: 72,
        sector: 'Открытая вода',
        location: 'озеро «Кульсай»',
        organizer: 'ФСРА',
        month: 'ЯНВАРЬ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.city,
        discipline: FishingDiscipline.iceFishing,
      ),
      TournamentModel(
        id: 'official_city_2',
        name: 'Чемпионат г. Алматы по спортивному лову форели на спиннинг',
        startDate: DateTime(2025, 3, 30),
        duration: 12,
        sector: 'Открытая вода',
        location: 'водохранилище "Fish-ка"',
        organizer: 'ФСРА',
        month: 'МАРТ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.city,
        discipline: FishingDiscipline.troutSpinning,
      ),
      TournamentModel(
        id: 'official_city_3',
        name: 'Чемпионат г. Алматы по спортивному лову рыбы на фидер',
        startDate: DateTime(2025, 7, 4),
        endDate: DateTime(2025, 7, 6),
        duration: 72,
        sector: 'Открытая вода',
        location: 'Водохранилище «Октябрьское-3»',
        organizer: 'ФСРА',
        month: 'ИЮЛЬ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.city,
        discipline: FishingDiscipline.feeder,
      ),
      TournamentModel(
        id: 'official_city_4',
        name: 'Чемпионат г. Алматы по спортивному лову карпа',
        startDate: DateTime(2025, 8, 14),
        endDate: DateTime(2025, 8, 17),
        duration: 72,
        sector: 'Открытая вода',
        location: 'Водохранилище «Казфиш»',
        organizer: 'ФСРА',
        month: 'АВГУСТ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.city,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'official_city_5',
        name: 'Чемпионат г. Алматы по спортивному лову рыбы на поплавочную удочку',
        startDate: DateTime(2025, 9, 20),
        endDate: DateTime(2025, 9, 21),
        duration: 48,
        sector: 'Открытая вода',
        location: 'Водохранилище «К-30»',
        organizer: 'ФСРА',
        month: 'СЕНТЯБРЬ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.city,
        discipline: FishingDiscipline.floatFishing,
      ),
      TournamentModel(
        id: 'official_city_6',
        name: 'Чемпионат г. Алматы по спортивному лову рыбы на спиннинг с лодок',
        startDate: DateTime(2025, 10, 3),
        endDate: DateTime(2025, 10, 5),
        duration: 72,
        sector: 'Открытая вода',
        location: 'Капчагайское вдхр.',
        organizer: 'ФСРА',
        month: 'ОКТЯБРЬ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.city,
        discipline: FishingDiscipline.spinningWithBoat,
      ),

      // РЕСПУБЛИКАНСКИЕ МЕРОПРИЯТИЯ
      TournamentModel(
        id: 'official_rep_1',
        name: 'Чемпионат РК по спортивному лову рыбы на мормышку',
        startDate: DateTime(2025, 3, 13),
        endDate: DateTime(2025, 3, 16),
        duration: 72,
        sector: 'Открытая вода',
        location: 'Карагандинская обл. Самаркандское вдхр.',
        organizer: 'ФСРРК',
        month: 'МАРТ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.regional,
        discipline: FishingDiscipline.iceFishing,
      ),
      TournamentModel(
        id: 'official_rep_2',
        name: 'Кубок РК по спортивному лову форели на спиннинг',
        startDate: DateTime(2025, 4, 11),
        endDate: DateTime(2025, 4, 13),
        duration: 72,
        sector: 'Открытая вода',
        location: 'Алматы водохранилище "Fish-ка"',
        organizer: 'ФСРРК',
        month: 'АПРЕЛЬ',
        type: TournamentType.cup,
        isOfficial: true,
        category: TournamentCategory.regional,
        discipline: FishingDiscipline.troutSpinning,
      ),
      TournamentModel(
        id: 'official_rep_3',
        name: 'Чемпионат РК по спортивному лову форели на спиннинг',
        startDate: DateTime(2025, 5, 16),
        endDate: DateTime(2025, 5, 18),
        duration: 72,
        sector: 'Открытая вода',
        location: 'г. Алматы водохранилище "Fish-ка"',
        organizer: 'ФСРРК',
        month: 'МАЙ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.regional,
        discipline: FishingDiscipline.troutSpinning,
      ),
      TournamentModel(
        id: 'official_rep_4',
        name: 'Чемпионат РК по спортивному лову карпа',
        startDate: DateTime(2025, 7, 19),
        endDate: DateTime(2025, 7, 27),
        duration: 192, // 8 дней
        sector: 'Открытая вода',
        location: 'Туркестанская обл. вдхр. Шардара',
        organizer: 'ФСРРК',
        month: 'ИЮЛЬ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.regional,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'official_rep_5',
        name: 'Чемпионат РК по спортивному лову рыбы на фидер',
        startDate: DateTime(2025, 8, 7),
        endDate: DateTime(2025, 8, 10),
        duration: 72,
        sector: 'Открытая вода',
        location: 'г. Алматы, Водохранилище «Октябрьское-3»',
        organizer: 'ФСРРК',
        month: 'АВГУСТ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.regional,
        discipline: FishingDiscipline.feeder,
      ),
      TournamentModel(
        id: 'official_rep_6',
        name: 'Чемпионат РК по спортивному лову рыбы на поплавочную удочку',
        startDate: DateTime(2025, 8, 28),
        endDate: DateTime(2025, 8, 31),
        duration: 72,
        sector: 'Открытая вода',
        location: 'г. Астана, река Есиль',
        organizer: 'ФСРРК',
        month: 'АВГУСТ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.regional,
        discipline: FishingDiscipline.floatFishing,
      ),
      TournamentModel(
        id: 'official_rep_7',
        name: 'Чемпионат РК по спортивному лову рыбы на спиннинг с лодок',
        startDate: DateTime(2025, 9, 4),
        endDate: DateTime(2025, 9, 7),
        duration: 72,
        sector: 'Открытая вода',
        location: 'ВКО Бухтарминское вдхр.',
        organizer: 'ФСРРК',
        month: 'СЕНТЯБРЬ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.regional,
        discipline: FishingDiscipline.spinningWithBoat,
      ),
      TournamentModel(
        id: 'official_rep_8',
        name: 'Чемпионат РК по спортивному лову рыбы "Street Fishing"',
        startDate: DateTime(2025, 9, 9),
        endDate: DateTime(2025, 9, 12),
        duration: 72,
        sector: 'Городская среда',
        location: 'г. Астана река Есиль',
        organizer: 'ФСРРК',
        month: 'СЕНТЯБРЬ',
        type: TournamentType.championship,
        isOfficial: true,
        category: TournamentCategory.regional,
        discipline: FishingDiscipline.streetFishing,
      ),
      TournamentModel(
        id: 'official_rep_9',
        name: 'Кубок РК по спортивному лову на спиннинг с лодок памяти Болата Турлыханова',
        startDate: DateTime(2025, 10, 23),
        endDate: DateTime(2025, 10, 26),
        duration: 72,
        sector: 'Открытая вода',
        location: 'Алматинская обл. Капчагайское вдхр.',
        organizer: 'ФСРРК',
        month: 'ОКТЯБРЬ',
        type: TournamentType.cup,
        isOfficial: true,
        category: TournamentCategory.regional,
        discipline: FishingDiscipline.spinningWithBoat,
      ),

      // МЕЖДУНАРОДНЫЕ МЕРОПРИЯТИЯ ЗА РУБЕЖОМ
      TournamentModel(
        id: 'official_world_1',
        name: 'Чемпионат мира по спортивному лову рыбы со льда на мормышку',
        startDate: DateTime(2025, 2, 10),
        endDate: DateTime(2025, 2, 17),
        duration: 168, // 7 дней
        sector: 'Лед',
        location: 'США штат Мичиган, озеро Тамарак',
        organizer: 'FIPSed',
        month: 'ФЕВРАЛЬ',
        type: TournamentType.worldChampionship,
        isOfficial: true,
        category: TournamentCategory.international,
        discipline: FishingDiscipline.iceFishing,
      ),
      TournamentModel(
        id: 'official_world_2',
        name: 'Чемпионат Мира по спортивному лову рыбы на фидер',
        startDate: DateTime(2025, 6, 9),
        endDate: DateTime(2025, 6, 16),
        duration: 168, // 7 дней
        sector: 'Открытая вода',
        location: 'Литва Русне, река Скирвит',
        organizer: 'FIPSed',
        month: 'ИЮНЬ',
        type: TournamentType.worldChampionship,
        isOfficial: true,
        category: TournamentCategory.international,
        discipline: FishingDiscipline.feeder,
      ),
      TournamentModel(
        id: 'official_world_3',
        name: 'УТС перед Чемпионатом мира по спортивному лову карпа',
        startDate: DateTime(2025, 8, 10),
        endDate: DateTime(2025, 8, 17),
        duration: 168, // 7 дней
        sector: 'Открытая вода',
        location: 'Хорватия',
        organizer: 'ФСРРК',
        month: 'АВГУСТ',
        type: TournamentType.trainingCamp,
        isOfficial: true,
        category: TournamentCategory.international,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'official_world_4',
        name: 'Чемпионат мира по спортивному лову карпа',
        startDate: DateTime(2025, 9, 15),
        endDate: DateTime(2025, 9, 21),
        duration: 144, // 6 дней
        sector: 'Открытая вода',
        location: 'Хорватия Даково, озеро Йосава',
        organizer: 'FIPSed',
        month: 'СЕНТЯБРЬ',
        type: TournamentType.worldChampionship,
        isOfficial: true,
        category: TournamentCategory.international,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'official_world_5',
        name: 'Чемпионат мира по спортивному лову рыбы на спиннинг с лодок',
        startDate: DateTime(2025, 10, 1),
        endDate: DateTime(2025, 10, 5),
        duration: 120, // 5 дней
        sector: 'Открытая вода',
        location: 'Эстония озеро Вортсьярв',
        organizer: 'FIPSed',
        month: 'ОКТЯБРЬ',
        type: TournamentType.worldChampionship,
        isOfficial: true,
        category: TournamentCategory.international,
        discipline: FishingDiscipline.spinningWithBoat,
      ),
      TournamentModel(
        id: 'official_world_6',
        name: 'Чемпионат Клубов по спортивному лову рыбы на фидер',
        startDate: DateTime(2025, 10, 6),
        endDate: DateTime(2025, 10, 13),
        duration: 168, // 7 дней
        sector: 'Открытая вода',
        location: 'Сербия Бела Церква канал DTD',
        organizer: 'FIPSed',
        month: 'ОКТЯБРЬ',
        type: TournamentType.clubChampionship,
        isOfficial: true,
        category: TournamentCategory.international,
        discipline: FishingDiscipline.feeder,
      ),
      TournamentModel(
        id: 'official_world_7',
        name: 'Чемпионат мира по спортивному лову форели на спиннинг',
        startDate: DateTime(2025, 11, 17),
        endDate: DateTime(2025, 11, 23),
        duration: 144, // 6 дней
        sector: 'Открытая вода',
        location: 'Италия Кампли озеро Веччио Мулино',
        organizer: 'FIPSed',
        month: 'НОЯБРЬ',
        type: TournamentType.worldChampionship,
        isOfficial: true,
        category: TournamentCategory.international,
        discipline: FishingDiscipline.troutSpinning,
      ),

      // МЕЖДУНАРОДНЫЕ МЕРОПРИЯТИЯ В РК
      TournamentModel(
        id: 'official_int_kz_1',
        name: 'Международный турнир по спортивному лову карпа "Carp KZ"',
        startDate: DateTime(2025, 9, 24),
        endDate: DateTime(2025, 9, 28),
        duration: 96, // 4 дня
        sector: 'Открытая вода',
        location: 'Акмолинская обл. Еремейтауский р-он, озеро Тойганколь',
        organizer: 'FIPSed, ФСРРК',
        month: 'СЕНТЯБРЬ',
        type: TournamentType.internationalTournament,
        isOfficial: true,
        category: TournamentCategory.internationalInKz,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'official_int_kz_2',
        name: 'Международный турнир по спортивному лову рыбы со льда на мормышку "Ice Masters 2025"',
        startDate: DateTime(2025, 12, 18),
        endDate: DateTime(2025, 12, 21),
        duration: 72,
        sector: 'Лед',
        location: 'Карагандинская обл. г. Темиртау, Самаркандское вдхр.',
        organizer: 'FIPSed, ФСРРК',
        month: 'ДЕКАБРЬ',
        type: TournamentType.internationalTournament,
        isOfficial: true,
        category: TournamentCategory.internationalInKz,
        discipline: FishingDiscipline.iceFishing,
      ),

      // === КОММЕРЧЕСКИЕ ТУРНИРЫ ===

      // МАЙ
      TournamentModel(
        id: 'com_may_1',
        name: 'Турнир в честь открытия озера "KazFish"',
        startDate: DateTime(2025, 5, 8),
        endDate: DateTime(2025, 5, 11),
        duration: 72,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Jetysu Carp Club',
        month: 'МАЙ',
        type: TournamentType.tournament,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_may_2',
        name: 'Открытый кубок "Jetysu Carp Club"',
        startDate: DateTime(2025, 5, 29),
        endDate: DateTime(2025, 6, 1),
        duration: 72,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Jetysu Carp Club',
        month: 'МАЙ',
        type: TournamentType.cup,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),

      // ИЮНЬ
      TournamentModel(
        id: 'com_jun_1',
        name: 'Кубок "Архи"',
        startDate: DateTime(2025, 6, 6),
        duration: 100,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Мечта Рыбака',
        month: 'ИЮНЬ',
        type: TournamentType.cup,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_jun_2',
        name: 'Кубок Касына',
        startDate: DateTime(2025, 6, 5),
        endDate: DateTime(2025, 6, 8),
        duration: 72,
        sector: '20',
        location: 'оз.К-28, г.Алматы',
        organizer: 'FDLr.Алматы',
        month: 'ИЮНЬ',
        type: TournamentType.cup,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_jun_3',
        name: 'KUKA PARTY',
        startDate: DateTime(2025, 6, 12),
        endDate: DateTime(2025, 6, 15),
        duration: 72,
        sector: '30',
        location: 'вдх.Шардара, Туркестанская область (г.Шардара)',
        organizer: 'CKK/Мечта Рыбака',
        month: 'ИЮНЬ',
        type: TournamentType.tournament,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_jun_4',
        name: 'Турнир "Family"',
        startDate: DateTime(2025, 6, 12),
        endDate: DateTime(2025, 6, 15),
        duration: 72,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Jetysu Carp Club',
        month: 'ИЮНЬ',
        type: TournamentType.tournament,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_jun_5',
        name: 'Кубок "Профи"',
        startDate: DateTime(2025, 6, 12),
        endDate: DateTime(2025, 6, 16),
        duration: 100,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Jetysu Carp Club',
        month: 'ИЮНЬ',
        type: TournamentType.cup,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_jun_6',
        name: 'Кубок "Мечта рыбака"',
        startDate: DateTime(2025, 6, 25),
        endDate: DateTime(2025, 6, 29),
        duration: 72,
        sector: '30',
        location: 'вдх.Шардара, Туркестанская область (г.Шардара)',
        organizer: 'Мечта Рыбака',
        month: 'ИЮНЬ',
        type: TournamentType.cup,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),

      // ИЮЛЬ
      TournamentModel(
        id: 'com_jul_1',
        name: 'Лига Чемпионов 1 этап',
        startDate: DateTime(2025, 7, 3),
        endDate: DateTime(2025, 7, 6),
        duration: 72,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Jetysu Carp Club',
        month: 'ИЮЛЬ',
        type: TournamentType.league,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_jul_2',
        name: 'Лига Чемпионов 2 этап',
        startDate: DateTime(2025, 7, 17),
        endDate: DateTime(2025, 7, 20),
        duration: 72,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Jetysu Carp Club',
        month: 'ИЮЛЬ',
        type: TournamentType.league,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_jul_3',
        name: 'Лига Чемпионов Финал',
        startDate: DateTime(2025, 7, 31),
        endDate: DateTime(2025, 8, 3),
        duration: 72,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Jetysu Carp Club',
        month: 'ИЮЛЬ',
        type: TournamentType.league,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),

      // АВГУСТ
      TournamentModel(
        id: 'com_aug_1',
        name: '"Gold Carp" большая коммерция',
        startDate: DateTime(2025, 8, 21),
        endDate: DateTime(2025, 8, 24),
        duration: 72,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Jetysu Carp Club',
        month: 'АВГУСТ',
        type: TournamentType.commercial,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),

      // СЕНТЯБРЬ
      TournamentModel(
        id: 'com_sep_1',
        name: 'Чемпионат КККК',
        startDate: DateTime(2025, 9, 3),
        endDate: DateTime(2025, 9, 7),
        duration: 100,
        sector: '30',
        location: 'вдх.Шардара, Туркестанская область',
        organizer: 'Клуб КККК',
        month: 'СЕНТЯБРЬ',
        type: TournamentType.championship,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_sep_2',
        name: 'Коммерческий турнир "Осенний Карп"',
        startDate: DateTime(2025, 9, 4),
        endDate: DateTime(2025, 9, 7),
        duration: 72,
        sector: '15',
        location: 'оз.Тополек, Область Абай (г.Семей)',
        organizer: 'ФСР области Абай/Карповый клуб Семей',
        month: 'СЕНТЯБРЬ',
        type: TournamentType.commercial,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_sep_3',
        name: 'Кубок Капитанов',
        startDate: DateTime(2025, 9, 11),
        endDate: DateTime(2025, 9, 14),
        duration: 72,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Jetysu Carp Club',
        month: 'СЕНТЯБРЬ',
        type: TournamentType.cup,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_sep_4',
        name: 'Чемпионат Алаш-SKK',
        startDate: DateTime(2025, 9, 19),
        endDate: DateTime(2025, 9, 21),
        duration: 72,
        sector: '30',
        location: 'вдх.Шардара, Туркестанская область',
        organizer: 'Алаш-SKK',
        month: 'СЕНТЯБРЬ',
        type: TournamentType.championship,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),

      // ОКТЯБРЬ
      TournamentModel(
        id: 'com_oct_1',
        name: 'Чемпионат "Жылы багыр"',
        startDate: DateTime(2025, 10, 9),
        endDate: DateTime(2025, 10, 12),
        duration: 72,
        sector: '30',
        location: 'вдх.Шардара, Туркестанская область',
        organizer: 'СКК',
        month: 'ОКТЯБРЬ',
        type: TournamentType.championship,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
      TournamentModel(
        id: 'com_oct_2',
        name: 'Закрытие сезона',
        startDate: DateTime(2025, 10, 9),
        endDate: DateTime(2025, 10, 12),
        duration: 72,
        sector: '15',
        location: 'вдх.KazFish, г.Алматы',
        organizer: 'Jetysu Carp Club',
        month: 'ОКТЯБРЬ',
        type: TournamentType.tournament,
        isOfficial: false,
        category: TournamentCategory.commercial,
        discipline: FishingDiscipline.carp,
      ),
    ];
  }

  // Фильтры
  List<TournamentModel> getOfficialTournaments() {
    return getAllTournaments().where((t) => t.isOfficial).toList();
  }

  List<TournamentModel> getCommercialTournaments() {
    return getAllTournaments().where((t) => !t.isOfficial).toList();
  }

  List<TournamentModel> getTournamentsByCategory(TournamentCategory category) {
    return getAllTournaments().where((t) => t.category == category).toList();
  }

  List<TournamentModel> getTournamentsByDiscipline(FishingDiscipline discipline) {
    return getAllTournaments().where((t) => t.discipline == discipline).toList();
  }

  List<TournamentModel> getTournamentsByMonth(String month) {
    return getAllTournaments().where((t) => t.month == month).toList();
  }

  List<TournamentModel> getTournamentsByType(TournamentType type) {
    return getAllTournaments().where((t) => t.type == type).toList();
  }

  List<TournamentModel> getUpcomingTournaments() {
    return getAllTournaments().where((t) => t.isFuture).toList();
  }

  List<TournamentModel> getActiveTournaments() {
    return getAllTournaments().where((t) => t.isActive).toList();
  }

  List<TournamentModel> getPastTournaments() {
    return getAllTournaments().where((t) => t.isPast).toList();
  }

  // Поиск
  List<TournamentModel> searchTournaments(String query) {
    final lowercaseQuery = query.toLowerCase();
    return getAllTournaments().where((t) =>
    t.name.toLowerCase().contains(lowercaseQuery) ||
        t.location.toLowerCase().contains(lowercaseQuery) ||
        t.organizer.toLowerCase().contains(lowercaseQuery)
    ).toList();
  }
}